const URLS = {
	currency: `${process.env.GATSBY_CURRENCY_ENDPOINT}`,
	site: `${process.env.GATSBY_SITE_DOMAIN}`,
	wp: `${process.env.GATSBY_WP_NUMBER}`,
	mailChimp: `${process.env.MAILCHIMP_ENDPOINT}`,
	baseAppUrl: `${process.env.GATSBY_BASE_APP_URL}`,
	getInTouch: `${process.env.GATSBY_GET_IN_TOUCH_URL}`,
	developer: `${process.env.GATSBY_DEVELOPER_URL}`,
	merchants: `${process.env.GATSBY_MERCHANT_URL}`,
	teaser: `${process.env.GATSBY_TEASER_URL}`,
	visa: `${process.env.GATSBY_VISA_URL}`,
	qatar: `${process.env.GATSBY_QATAR_URL}`,
	qatarCui: `${process.env.GATSBY_QATAR_CUI_URL}`,
	qatarEndpoint: `${process.env.GATSBY_QATAR_CUI_ENDPOINT}`,
	tagManagerID: `${process.env.TAG_MANAGER_ID}`,
	googleID: `${process.env.GOOGLE_ANALYTICS_ID}`,
	signUpFarmers: `${process.env.GATSBY_SIGN_UP_FARMERS_URL}`,
	basesAndConditions: `${process.env.GATSBY_BASES_AND_CONDITIONS_PROMOTIONS}`,
};
export default URLS;
